"""Pitch user and category relationship

Revision ID: 970e368d9f7a
Revises: 9435fec03445
Create Date: 2021-11-12 20:40:11.277365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970e368d9f7a'
down_revision = '9435fec03445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('pitch', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitch', 'pitch_category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'pitch', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'user_id')
    op.drop_column('pitch', 'category_id')
    # ### end Alembic commands ###
