"""Password

Revision ID: c0db52ca7b4f
Revises: 
Create Date: 2021-11-12 13:12:33.631333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0db52ca7b4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
